FROM quay.io/aptible/debian:wheezy

ENV MONGO_VERSION <%= ENV.fetch "MONGO_VERSION" %>
ENV MONGO_SHA1SUM <%= ENV.fetch "MONGO_SHA1SUM" %>
ENV MONGO_GPG_KEY <%= ENV.fetch "MONGO_GPG_KEY" %>

# Add MongoDB repository
ADD <%= ENV.fetch 'TAG' %>/templates/mongodb.list /etc/apt/sources.list.d/mongodb.list
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv "$MONGO_GPG_KEY"

# Install MongoDB core
ADD <%= ENV.fetch 'TAG' %>/install-mongodb.sh /install-mongodb.sh
RUN /install-mongodb.sh

# Install MongoDB tools and utilities we need
RUN apt-install "mongodb-org-tools=${MONGO_VERSION}" adduser procps ca-certificates python

# Configuration
ENV MONGO_SSL_MODE <%= ENV.fetch "MONGO_SSL_MODE" %>
ENV DATA_DIRECTORY /var/db
ENV SSL_DIRECTORY /etc/ssl/mongo
RUN mkdir -p "${DATA_DIRECTORY}" "${SSL_DIRECTORY}"

# Tools
ADD bin/run-database.sh /usr/bin/
ADD bin/parse_mongo_url.py /usr/bin/
ADD bin/utilities.sh /usr/bin/

# Integration tests
ADD <%= ENV.fetch 'TAG' %>/test /tmp/test
ADD test /tmp/test
RUN bats /tmp/test

VOLUME ["$DATA_DIRECTORY"]
VOLUME ["$SSL_DIRECTORY"]
EXPOSE 27017

ENTRYPOINT ["run-database.sh"]
